env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - import
  - prettier
ignorePatterns:
  - dist
rules:
  prettier/prettier: error
